name: helloGithubAction

on: 
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: 1. 파일 목록 출력
      run: ls -al
    
    - name: 2. 파이썬 패키지 확인 
      run: pip list
    
    - name: 3. pip 업그레이드 
      run: python -m pip install --upgrade pip
    
    - name: 4. 필요한 패키지 install 
      run: pip install -r requirements.txt

    - name: 5. 파이썬 실행 
      run: python test.py


